=== cosmin-vestemean/retailers/documentatie/DXF KAUFLAND ROMANIA Electronic Invoice/XSD feedback message/docxchange-message.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) Docprocess S.R.L. 2015. All Rights Reserved.
  ~
  ~ No part of software may be distributed or reproduced without
  ~ Docprocess S.R.L.'s express consent.
  -->
<!-- versiunea 11112015 13.30 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" elementFormDefault="qualified" jaxb:version="2.0">
	<xs:element name="DXMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="MessageDate"/>
				<xs:element ref="MessageTime"/>
				<xs:element ref="MessageOrigin"/>
				<xs:element ref="DocumentReference"/>
				<xs:element ref="DocumentUID"/>
				<xs:element ref="SupplierReceiverCode"/>
				<xs:element ref="DocumentResponse"/>
				<xs:element ref="DocumentDetail"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MessageDate" type="xs:date"/>
	<xs:element name="MessageTime" type="xs:time"/>
	<xs:element name="MessageOrigin" type="xs:string"/>
	<xs:element name="DocumentReference" type="xs:string"/>
	<xs:element name="DocumentUID" type="xs:string"/>
	<xs:element name="SupplierReceiverCode" type="xs:string"/>
	<xs:element name="DocumentResponse" type="xs:string"/>
	<xs:element name="DocumentDetail" type="xs:string"/>
</xs:schema>

=== cosmin-vestemean/retailers/documentatie/XML feedback message - sample/APERAK_DX01_005_20151123_01000022_VAT_RO17275880.xml
<?xml version="1.0" encoding="UTF-8"?>
<DXMessage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://dx.docxchange.ro/schemas/docxchange-message/11112015_1330/docxchange-message.xsd">
   <MessageDate>2015-11-23</MessageDate>
   <MessageTime>15:48:30+02:00</MessageTime>
   <MessageOrigin>RO17275880</MessageOrigin>
   <DocumentReference>123456</DocumentReference>
   <DocumentUID>DXTEST01_099_20151123_01000014</DocumentUID>
   <SupplierReceiverCode>222222</SupplierReceiverCode>
   <DocumentResponse>ACCEPTAT</DocumentResponse>
   <DocumentDetail>
ID factura: DX01_099_20151123_01000014 
Nume fisier: Factura123456_RO222.xml 
Status: Transmis la client 
Mesaj: Factura procesata de platforma DocXchange si livrata la client
</DocumentDetail>
</DXMessage>

=== cosmin-vestemean/retailers/data/aperak/xml/APERAK_DX01_005_20240131_01032588_VAT_RO17275880.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DXMessage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:/Users/rlixandru/Downloads/docxchange-message.xsd">
	<MessageDate>2024-01-31</MessageDate>
	<MessageTime>16:13:10</MessageTime>
	<MessageOrigin>RO17275880</MessageOrigin>
	<DocumentReference>Necunoscut</DocumentReference>
	<DocumentUID>DX01_099_20240131_01007247</DocumentUID>
	<SupplierReceiverCode>Necunoscut</SupplierReceiverCode>
	<DocumentResponse>RECEPTIONAT</DocumentResponse>
	<DocumentDetail>- - 
ID document: DX01_099_20240131_01007247 
Nume fisier: INVOIC_18854_VAT_RO25190857.xml
Status: Primit de DX 
Mesaj: Documentul a fost receptionat de platforma DocXchange
The document has been received by DocXchange platform.</DocumentDetail>
</DXMessage>

=== cosmin-vestemean/retailers/data/aperak/xml/APERAK_DX01_005_20240301_01024160_VAT_RO13348610.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DXMessage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:/Users/rlixandru/Downloads/docxchange-message.xsd">
	<MessageDate>2024-03-01</MessageDate>
	<MessageTime>13:13:03</MessageTime>
	<MessageOrigin>RO13348610</MessageOrigin>
	<DocumentReference>19521</DocumentReference>
	<DocumentUID>DX01_099_20240301_03001172</DocumentUID>
	<SupplierReceiverCode>114221</SupplierReceiverCode>
	<DocumentResponse>IN ASTEPTARE</DocumentResponse>
	<DocumentDetail>- - FACTURA TRIMISA - Factura trimisa la retailer</DocumentDetail>
</DXMessage>

=== cosmin-vestemean/retailers/data/aperak/xml/APERAK_DX01_005_20240202_01022850_VAT_RO33067767.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DXMessage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:/Users/rlixandru/Downloads/docxchange-message.xsd">
	<MessageDate>2024-02-02</MessageDate>
	<MessageTime>11:44:03</MessageTime>
	<MessageOrigin>RO33067767</MessageOrigin>
	<DocumentReference>18972</DocumentReference>
	<DocumentUID>DX01_099_20240202_01004052</DocumentUID>
	<SupplierReceiverCode>15121</SupplierReceiverCode>
	<DocumentResponse>RECEPTIONAT</DocumentResponse>
	<DocumentDetail>- - Mesaj preluat de la client - pentru informatii suplimentare va rugam sa-i contactati la sectiunea Suport Tehnic a Portalului WEB Carrefour / Message received from the customer - for additional information please contact them in the Technical Support section of the Carrefour WEB Portal / 1111 - Factura a fost receptionata de sistemul Carrefour.</DocumentDetail>
</DXMessage>

=== cosmin-vestemean/retailers/data/aperak/xml/APERAK_DX01_005_20240131_01032600_VAT_RO17275880.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DXMessage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:/Users/rlixandru/Downloads/docxchange-message.xsd">
	<MessageDate>2024-01-31</MessageDate>
	<MessageTime>16:13:23</MessageTime>
	<MessageOrigin>RO17275880</MessageOrigin>
	<DocumentReference>18853</DocumentReference>
	<DocumentUID>DX01_099_20240131_01007246</DocumentUID>
	<SupplierReceiverCode>10011546</SupplierReceiverCode>
	<DocumentResponse>ACCEPTAT</DocumentResponse>
	<DocumentDetail>- - 
ID document: DX01_099_20240131_01007246 
Nume fisier: INVOIC_18853_VAT_RO25190857.xml
Status: Transmis la client 
Mesaj: Document procesat de platforma DocXchange si livrat la client
Document processed by DocXchange platform and delivered to the customer
</DocumentDetail>
</DXMessage>

=== cosmin-vestemean/retailers/data/aperak/xml/APERAK_DX01_005_20240131_01003664_VAT_RO17275880.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DXMessage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:/Users/rlixandru/Downloads/docxchange-message.xsd">
	<MessageDate>2024-01-31</MessageDate>
	<MessageTime>05:04:36</MessageTime>
	<MessageOrigin>RO17275880</MessageOrigin>
	<DocumentReference>DPR14834</DocumentReference>
	<DocumentUID>DX01_099_20240131_01000455</DocumentUID>
	<SupplierReceiverCode>RO25190857</SupplierReceiverCode>
	<DocumentResponse>ACCEPTAT</DocumentResponse>
	<DocumentDetail>- - 
ID document: DX01_099_20240131_01000455 
Nume fisier: INVOIC_1706670005767_INVOIC20240131DPR14834VATRO17275880_VAT_RO17275880.csv
Status: Transmis la client 
Mesaj: Document procesat de platforma DocXchange si livrat la client
Document processed by DocXchange platform and delivered to the customer
</DocumentDetail>
</DXMessage>

=== cosmin-vestemean/retailers/data/aperak/xml/APERAK_DXjA7tmryGK9dfiC0YVzmrvA_VAT_RO17275880.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DXMessage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="file:///C:/Users/rlixandru/Downloads/docxchange-message.xsd">
	<MessageDate>2023-10-04</MessageDate>
	<MessageTime>15:18:38</MessageTime>
	<MessageOrigin>RO17275880</MessageOrigin>
	<DocumentReference>INVOIC_16850_VAT_RO25190857.xml</DocumentReference>
	<DocumentUID>DXDqGWNEPEcXJmVRGWbisJHQ</DocumentUID>
	<SupplierReceiverCode>-</SupplierReceiverCode>
	<DocumentResponse>RECEPTIONAT</DocumentResponse>
	<DocumentDetail>- - ID document: DXDqGWNEPEcXJmVRGWbisJHQ Nume fisier:
		INVOIC_16850_VAT_RO25190857.xml Status: Receptionat de destinatar / Received by recipient
		Mesaj: Documentul a fost primit de cÄtre destinatar. The document has been received by the
		recipient.</DocumentDetail>
</DXMessage>

=== cosmin-vestemean/retailers/data/aperak/xml/APERAK_DX01_005_20240131_01034351_VAT_RO15991149.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DXMessage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:/Users/rlixandru/Downloads/docxchange-message.xsd">
	<MessageDate>2024-01-31</MessageDate>
	<MessageTime>16:20:49</MessageTime>
	<MessageOrigin>RO15991149</MessageOrigin>
	<DocumentReference>18853</DocumentReference>
	<DocumentUID>DX01_099_20240131_01007246</DocumentUID>
	<SupplierReceiverCode>10011546</SupplierReceiverCode>
	<DocumentResponse>RECEPTIONAT</DocumentResponse>
	<DocumentDetail>- - 
ID document: DX01_099_20240131_01007246
Nume fisier: null
AS2MessageID: KAUFLAND-AS2-NEW-20240131-162039283-VuvP
MessageDigestNotificationID: KAUFLAND-AS2-NEW-20240131-162039283-VuvP
Status: Receptionat de Client
Mesaj: Documentul a fost receptionat de catre client
The document has been received by the customer.
</DocumentDetail>
</DXMessage>
